#ifndef TIMESINCELIBRARY_GLOBAL_H
#define TIMESINCELIBRARY_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TIMESINCELIBRARY_LIBRARY)
#  define TIMESINCELIBRARYSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TIMESINCELIBRARYSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TIMESINCELIBRARY_GLOBAL_H
